spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:companydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
truproxy:
  host: https://exercise.trunarrative.cloud
  companies-path: /TruProxyAPI/rest/Companies/v1/search?Query={search_term}
  officers-path: /TruProxyAPI/rest/Companies/v1/Officers?CompanyNumber={company_number}


